# Generated by Django 4.2.5 on 2024-03-17 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xo_back_app', '0002_alter_games_lastmoveuser_alter_games_user2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='lastMoveUser',
            new_name='move',
        ),
    ]
