# Generated by Django 4.2.5 on 2024-03-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xo_back_app', '0003_rename_lastmoveuser_games_move'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='finish',
            field=models.CharField(max_length=255, default=0, null=False, blank=False),
        ),
    ]
