# Generated by Django 4.2.5 on 2024-03-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.CharField(max_length=255)),
                ('user2', models.CharField(max_length=255)),
                ('lastMoveUser', models.CharField(max_length=255)),
                ('whatMove', models.CharField(max_length=255)),
            ],
        ),
    ]
