# Generated by Django 4.2.5 on 2024-03-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xo_back_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='lastMoveUser',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='games',
            name='user2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='games',
            name='whatMove',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
